server:
  port: 7001
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false   #是否将自己注册到eureka中
    fetch-registry: false         #是否从eureka中获取信息
    service-url:
      defaultZone: http://localhost:7001/eureka/
spring:
  application:
    name: eureka