server:
  port: 8001

spring:
  application:
    name: cloud-provider-hystrix-payment-service8001

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/